pyjong/authentication/views.py
from flask import Blueprint,render_template,redirect,url_for,flash,session,abort,request
from pyjong import db,bcrypt
from pyjong.models import UserData,duplicate_username_email_check,username_password_check,get_friends_list,new_game_update
from pyjong.authentication.forms import Login,SignUp
from flask_login import login_user,login_required,logout_user,current_user
import datetime

authentication_blueprint = Blueprint('authentication',__name__,template_folder='templates/authentication')







##################################################
##################################################
##Views for Authentication##
###########################


@authentication_blueprint.route('/login',methods=['GET','POST'])
def login():

    form = Login()

    if form.validate_on_submit():
        user = UserData.query.filter_by(username=form.username.data).first()
        #check if username and password are correct
        if user:
            if user.check_password(form.password.data):
                login_user(user)
                #update session info for use with other request checks
                session['username'] = form.username.data
                session['updated'] = False
                session['in_room'] = False
                session['has_new_invites'] = False
                session['players'] = 1
                session['requests'] = []
                get_friends_list(session['username'])
                next = request.args.get('next')
                #check if user was redirected, and send them to the page they were trying to access before login
                if next == None or not next[0] == '/':
                    flash(f"ログインできました。お帰りなさい、{current_user.username}。",'alert-success')
                    return redirect(url_for('index'))
                else:
                    flash(f"ログインできました。お帰りなさい、{current_user.username}。",'alert-success')
                    return redirect(next)
        else:
            flash('パスワードもしくはユーザーネームが間違っていたようです。','alert-danger')
            return render_template('login.html',form=form)

    return render_template('login.html',form=form)

@authentication_blueprint.route('/signup',methods=['GET','POST'])
def signup():

    form = SignUp()

    if form.validate_on_submit():
        #check username to see if no duplicates in db
        if duplicate_username_email_check(form.username.data,form.email_address.data):
            #save data to database
            new_user = UserData(username=form.username.data,email_address=form.email_address.data,password=form.password.data,friends_list="[]",friend_requests="[]",invites="[]",kyoku_win_count=0,game_win_count=0,points=0)
            db.session.add(new_user)
            db.session.commit()
            #update session info for use with other request checks
            session['updated'] = False
            session['username'] = form.username.data
            session['in_room'] = False
            session['has_new_invites'] = False
            session['players'] = 1
            session['requests'] = []
            login_user(new_user)
            #add update to board of new player registration
            new_game_update(text=f"{form.username.data}が新しくPyJongに登録しました！友達リクエストを送りましょう！")
            flash(f"{current_user.username}、登録できました！",'alert-success')
            return redirect(url_for('index'))
        #send user back to signup page and display duplicate username error
        else:
            flash('ユーザーネームもしくはメールアドレスはすでに登録されている','alert-danger')
            return render_template('signup.html',form=form)
    return render_template('signup.html',form=form)

pyjong/main/views.py
from flask import Blueprint,render_template,redirect,url_for,flash,session
from flask_login import login_required,current_user
from pyjong import db,room_players
from pyjong.models import UserData,retrieve_game_updates,add_friend,delete_friend,send_request,get_new_requests,get_friends_list,get_invites,send_invite
from pyjong.main.forms import FriendRequest,AcceptFriendRequest,DeleteFriend,InviteFriend,AcceptInvite,PlaySolo,LeaveRoom
import datetime
from time import time

main_blueprint = Blueprint('main',__name__,template_folder='templates/main')

#initialise socketiofunctions
from pyjong.apps.socketioapps import chat,mahjongsocketio


##########FORM FUNCTIONS
#function to generate friend lists for invite choice
def add_friends_to_form(form):
    if len(session['friends']) > 0:
        form.select_friend.choices = [(usr,usr) for usr in session['friends']]
        session['has_friends'] = True
    else:
        session['has_friends'] = False
    return form
#function to generate friend lists for invite choice
def add_friends_to_form(form):
    if len(session['friends']) > 0:
        form.select_friend.choices = [(usr,usr) for usr in session['friends']]
        session['has_friends'] = True
    else:
        session['has_friends'] = False
    return form
#function to add friend requests to form
def add_friend_requests_to_form(form):
    if session['new_requests']:
        form.select_friend.choices = [(usr,usr) for usr in session['requests']]
    else:
        form.select_friend.choices = [('no_friends','友達はまだいないようです')]
    return form
def add_invites_to_form(form):
    if session['has_new_invites']:
        form.select_friend.choices = [(room,usr) for usr,room in session['invites']]
    else:
        pass
    return form

#######################################################

#####ROUTE FUNCTIONS

@main_blueprint.route('/info')
def info():
    return render_template('info.html')

@main_blueprint.route('/leaveroom',methods=['POST','GET'])
def leaveroom():
    session['players'] = 1
    session['in_room'] = False
    return redirect(url_for('main.friends'))

@main_blueprint.route('/game',methods=['GET','POST'])
@login_required
def game():
    #forms
    form = InviteFriend()
    form = add_friends_to_form(form)
    solo_form = PlaySolo()
    leaveroom_form = LeaveRoom()


    if session['in_room']:
        name = session['username']
        room = session['room']
        return render_template('game.html',form=form,name=name,room=room,leaveroom_form=leaveroom_form)


    #validation check for invite
    if form.validate_on_submit():
        send_invite(session_username=current_user.username,invited_username=form.select_friend.data,room=form.room_name.data)
        session['room'] = form.room_name.data
        session['in_room'] = True
        session['players'] = 2
        #set inviter as player one
        session['player_id'] = 1
        #add names to variable to be accessed on game 0=player1_name,1=player3_name
        room_players[session['room']] = [session['username'],form.select_friend.data]

        flash("招待状を送りました！",'alert-success')
        return redirect(url_for('main.game'))
    #setup solo room
    if solo_form.validate_on_submit():
        session['room'] = str(int(time()))
        session['players'] = 1
        session['in_room'] = True
        session['player_id'] = 1
        #set name for player2 to none
        room_players[session['room']] = [session['username'],None]
        return redirect(url_for('main.game'))


    return render_template('game.html',form=form,solo_form=solo_form,leaveroom_form=leaveroom_form)

@main_blueprint.route('/friends',methods=['GET','POST'])
@login_required
def friends():

    #update information
    get_new_requests(current_user.username)
    get_invites(current_user.username)
    get_friends_list(current_user.username)
    #add choices to forms
    form_delete = DeleteFriend()
    form_delete = add_friends_to_form(form_delete)
    form_req = FriendRequest()
    form_add = AcceptFriendRequest()
    form_add = add_friend_requests_to_form(form_add)
    accept_invite_form = AcceptInvite()
    accept_invite_form = add_invites_to_form(accept_invite_form)
    game_updates = retrieve_game_updates()


    #check all forms for positive return
    if accept_invite_form.validate_on_submit():
        #room name is linked to select_friend value
        session['room'] = accept_invite_form.select_friend.data
        session['in_room'] = True
        session['players'] = 2
        #set joining user as player 2
        session['player_id'] = 2
        flash(f"{session['room']}に入りました！","alert-success")
        return redirect(url_for('main.game'))
    if form_delete.validate_on_submit():
        delete_friend(requested_username=form_delete.select_friend.data,requester_username=current_user.username)
        flash("友達を削除しました。",'alert-success')
        return redirect(url_for('main.friends'))
    if form_req.validate_on_submit():
        if send_request(requester_username=current_user.username,requested_username=form_req.username.data):
            flash(f'{form_req.username.data}にリクエストを送りました！','alert-success')
            return redirect(url_for('main.friends'))
        else:
            flash('入力に問題があるようです。すでにリクエストを送ったか、ユーザーネームが間違っていないかご確認ください。','alert-warning')
            return redirect(url_for('main.friends'))
    if form_add.validate_on_submit():
        for friend in form_add.select_friend.data:
            add_friend(requested_username=current_user.username,requester_username=friend)
        session['new_requests'] = False
        session['requests'] = []
        flash('友達を追加しました！','alert-success')
        return redirect(url_for('main.friends'))
    return render_template('friends.html',form_delete=form_delete,form_add=form_add,form_req=form_req,accept_invite_form=accept_invite_form,game_updates=game_updates)

pyjong/templates/base.html
<!DOCTYPE html>
<html lang="jp" dir="ltr">
  <head>
    <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>PyJong</title>

    <!-- google font imports -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300&display=swap" rel="stylesheet">

    <!-- javascript/socketio imports -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.1.3/socket.io.js" integrity="sha512-PU5S6BA03fRv1Q5fpwXjg5nlRrgdoguZ74urFInkbABMCENyx5oP3hrDzYMMPh3qdLdknIvrGj3yqZ4JuU7Nag==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <!-- bootstrap imports -->
    <link href="https://storage.googleapis.com/pyjong-static/pyjong/static/styles/bootstrap.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

  </head>
  <body class="d-flex flex-column h-100">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{url_for('index')}}">PyJong</a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        {% if current_user.is_authenticated %}
        <li class="nav-item">
        <a class="nav-link active" href="{{url_for('logout')}}">ログアウト</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{{url_for('main.game')}}">ゲーム</a>
        </li>
        {% else %}
        <li class="nav-item">
        <a class="nav-link active" href="{{url_for('authentication.login')}}">ログイン</a>
        </li>
        <li class="nav-item">
            <a class="nav-link active" href="{{url_for('authentication.signup')}}">登録</a>
        </li>
        {% endif %}



        <li class="nav-item">
          <a class="nav-link" href="{{url_for('main.info')}}">PyJongについて</a>
        </li>
      </ul>
    </div>
  </div>
  </nav>

{% with messages = get_flashed_messages(with_categories=True) %}
 {% if messages %}
 {% for category,message in messages %}
 <div class="alert {{ category }} alert-dismissible fade show" role="alert">
 {{message}}
 <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% endwith %}

  {% block content %}

  {% endblock %}

  </body>
</html>

pyjong/templates/home.html
<!DOCTYPE html>
{% extends "base.html" %}

{% block content %}
<div class="container text-center pt-2">
  <h1 class="px-3">PyJongへようこそ！</h1>
</div>


<div class="container py-3 px-5 text-center">
  <p class="lead">PyJongは、PythonとJavaScriptで開発された、無料麻雀アプリです。</p>
</div>
  <p class="text-center">
  <a href="{{url_for('authentication.login')}}" class="btn btn-secondary my-2 mx-1">ログインのページはこちら</a>
  <a href="{{url_for('authentication.signup')}}" class="btn btn-secondary my-2 mx-1">新しいメンバーは新規登録へ</a>
  </p>

</div>
<div class="container pt-2 pb-5">
  <h3>ユーザーの近況：</h3>
  <ul class="list-group pt-1">
    {% for update in game_updates.items %}
    <li class="list-group-item bg-secondary text-white">
      <small>{{update.date.strftime('%D %H:%M:%S')}}</small>
      <br>
      <p>{{update.text}}</p>
    </li>
    {% endfor %}
  </ul>

</div>

{% endblock %}